//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabiAsp
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int id { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public string rating { get; set; }
        public string location { get; set; }
        public string Time { get; set; }
        public string Price { get; set; }
        public string DeliveryFee { get; set; }
        public string minOrder { get; set; }
        public string isDeleted { get; set; }
        public Nullable<int> SCid { get; set; }
        public Nullable<int> itemAvailible { get; set; }
        public Nullable<int> SoldItems { get; set; }
    
        public virtual SubCategory SubCategory { get; set; }
    }
}
