//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabiAsp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class sabiShopEntities : DbContext
    {
        public sabiShopEntities()
            : base("name=sabiShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Shop> Shops { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<Tracking> Trackings { get; set; }
        public virtual DbSet<UserChat> UserChats { get; set; }
        public virtual DbSet<UserItemCard> UserItemCards { get; set; }
        public virtual DbSet<UserMessage> UserMessages { get; set; }
        public virtual DbSet<UserMessageRecipient> UserMessageRecipients { get; set; }
        public virtual DbSet<UserRating> UserRatings { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<vendor> vendors { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
    
        public virtual ObjectResult<GetUserChat_Result> GetUserChat(Nullable<int> groupId, Nullable<int> senderId, Nullable<int> recipientId)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var senderIdParameter = senderId.HasValue ?
                new ObjectParameter("SenderId", senderId) :
                new ObjectParameter("SenderId", typeof(int));
    
            var recipientIdParameter = recipientId.HasValue ?
                new ObjectParameter("RecipientId", recipientId) :
                new ObjectParameter("RecipientId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserChat_Result>("GetUserChat", groupIdParameter, senderIdParameter, recipientIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GetUserGroup(Nullable<int> senderId, Nullable<int> recipientId)
        {
            var senderIdParameter = senderId.HasValue ?
                new ObjectParameter("SenderId", senderId) :
                new ObjectParameter("SenderId", typeof(int));
    
            var recipientIdParameter = recipientId.HasValue ?
                new ObjectParameter("RecipientId", recipientId) :
                new ObjectParameter("RecipientId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetUserGroup", senderIdParameter, recipientIdParameter);
        }
    
        public virtual ObjectResult<GetUserInfoByVendorId_Result> GetUserInfoByVendorId(Nullable<int> vendorid)
        {
            var vendoridParameter = vendorid.HasValue ?
                new ObjectParameter("Vendorid", vendorid) :
                new ObjectParameter("Vendorid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserInfoByVendorId_Result>("GetUserInfoByVendorId", vendoridParameter);
        }
    
        public virtual ObjectResult<GetUserWithGroup_Result> GetUserWithGroup(Nullable<int> recipientId)
        {
            var recipientIdParameter = recipientId.HasValue ?
                new ObjectParameter("RecipientId", recipientId) :
                new ObjectParameter("RecipientId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserWithGroup_Result>("GetUserWithGroup", recipientIdParameter);
        }
    }
}
