//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabiAsp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        public int trackingId { get; set; }
        public Nullable<int> to { get; set; }
        public Nullable<int> from { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string Description { get; set; }
        public string step1 { get; set; }
        public string step2 { get; set; }
        public string step3 { get; set; }
        public string state { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<int> isModified { get; set; }
        public string isCreated { get; set; }
        public string ordernumber { get; set; }
    
        public virtual item item { get; set; }
        public virtual vendor vendor { get; set; }
        public virtual user user { get; set; }
    }
}
