//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabiAsp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class u4
    {
        public double Mobile { get; set; }
        public string NAME { get; set; }
        public string Address { get; set; }
        public string CNIC { get; set; }
        public string COUNTRY_NAME { get; set; }
    }
}
