//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabiAsp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMessageRecipient
    {
        public int MessageRecipientId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> MessageId { get; set; }
        public Nullable<int> UserGroupId { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual UserGroup UserGroup { get; set; }
        public virtual UserMessage UserMessage { get; set; }
        public virtual user user { get; set; }
    }
}
